FROM rust:1.69-slim-bullseye AS base-builder
WORKDIR /app
COPY ./linkresolver/Cargo.toml ./linkresolver/
RUN cd linkresolver && mkdir src && touch src/lib.rs
WORKDIR /app/linkresolver
RUN cargo build --release

FROM base-builder AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin tools-linkresolver

FROM gcr.io/distroless/cc AS runner
WORKDIR /app
COPY --from=builder /app/target/release/tools-linkresolver .
CMD ["./tools-linkresolver"]