FROM rust:1.69-slim-bullseye AS base-builder
RUN apt update && apt install -y cmake g++
WORKDIR /app
COPY ./mailer/Cargo.toml ./mailer/
RUN cd mailer && mkdir src && touch src/lib.rs
WORKDIR /app/mailer
RUN cargo build --release

FROM base-builder AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin tools-mailer

FROM gcr.io/distroless/cc AS runner
WORKDIR /app
COPY --from=builder /app/target/release/tools-mailer .
CMD ["./tools-mailer"]