[package]
name = "tools-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-cors = "0.7"
actix-web-httpauth = "0.8"
async-graphql = { version = "7", features = ["uuid", "chrono"] }
async-graphql-actix-web = "7"                                                 # If you need to integrate into actix-web
tonic = "0.12"
prost = "0.13"
diesel = { version = "2", features = ["postgres", "r2d2", "uuid", "chrono"] }
diesel_migrations = "2"
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }
chrono = "0.4"

tools-account = { path = "../account" }
tools-link = { path = "../link" }
tools-apprepo = { path = "../apprepo" }
tools-lib-db = { path = "../lib/db" }
